version: '3.8'

services:
  db:
    container_name: o_cinema
    image: postgres:latest  # Используем официальный образ PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
    ports:
      - "5438:5432"
    volumes:
      - cinema_volume:/var/lib/postgresql/data  # Храним данные даже после перезапуска контейнера
volumes:
  cinema_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:/GitHub/online_cinema/database'

