version: '3.8'

services:
  db:
    container_name: o_cinema
    image: postgres:latest  # Используем официальный образ PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
    ports:
      - "5438:5432"
    volumes:
      - /GitHub/online_cinema/database:/var/lib/postgresql/data  # Храним данные даже после перезапуска контейнера
