FROM postgres:latest  # Берем свежую версию PostgreSQL

ENV POSTGRES_DB=cinema_db          # Название базы данных
ENV POSTGRES_USER=cinema_user      # Имя пользователя
ENV POSTGRES_PASSWORD=cinema_password  # Пароль для базы данных

EXPOSE 5432  # Открываем порт 5432 (на нем работает PostgreSQL)
